### ISSUE TITLE
Space size

### ISSUE THREAD

**Issue by UFO-84** [SociallyDev/Spaces-API#49]
Is there any way to get total space used in a space using your API?

**Comment by SociallyDev** [comment]
Hey,
So there is a way to get the entire Space's storage size. It involves iterating over all the objects that exist in the bucket to get the total size:
```php
$my_space = Spaces("ACCESS KEY", "SECRET KEY")->space("my_space", "nyc3");


$size = 0;
foreach ($my_space->listFiles() as $file) {
  $size += $file["Size"];
}

//$size should hold the total bucket total size.
```

**Comment by UFO-84** [comment]
Thanks for the quick reply. 

The way you mentioned will do the job but if I have huge objects in the space, it will be a pain. 

Anyway, thanks again. I will make a cron/queue process to maintain space size.

**Comment by SociallyDev** [comment]
Yes, I know. Unfortunately, this is the only method possible because I don't think there is a general object that lets you know the total size of a Space, and DigitalOcean's own API has no references to it either.

Another thing you could do is keep a tally of total size in your own database (Increased whenever you upload an object, decreased whenever you delete one).
