### ISSUE TITLE
ObjectURL sometimes incoherent

### ISSUE THREAD

**Issue by adadgio** [SociallyDev/Spaces-API#51]
When I upload videos, I randomly get two different kinds of ObjectURL in the ::$my_space->uploadFile result:

`https://med-cdn.ams3.digitaloceanspaces.com/myurl.mp4`

And sometimes something like: `ams3.digitaloceanspaces.com/med-cdn/myurl.mp4` (without https, but file is still uploaded)

The video is still correctly uploaded. Have someone experienced it ? Not sure if this might ba an issue of this bundle, digital ocean or amazon s3...

**Comment by SociallyDev** [comment]
Hey @adadgio ,
Technically, both URLs are correct (S3 supports bucket names as a URL parameter instead of a CNAME subdomain).
This does seem to come directly from either DigitalOcean or AWS's API.
You can see how Spaces-API hands this request off here:
https://github.com/SociallyDev/Spaces-API/blob/28fbd13ef647dbbf70ade274d1fd86fb4919c8ee/spaces.php#L169
It just returns an optimized version of the result (With no edits to URLs) obtained here.

One thing you could do is build URLs on your own (It's especially helpful if you planning on using a custom domain!):
Here's how that should work:
```php
$url = "https://space.mydomain.com/".$objectName; //You set this name while uploading anyway!
```
You can also get the name from the object returned as the `Key` property.

Hope this helped!

**Comment by adadgio** [comment]
Yep, that's what i though as well. I am building the URL myself as a workaround. But it's somewhat strange that it would give a different constructed URL (especially without the "https" part), and really incoherent from their API...

Thanks for the reply anyways!
